In [1]:
!pip install numpy
!pip install gym

  Created wheel for gym: filename=gym-0.18.3-py3-none-any.whl size=1657522 sha256=b872315dbfe93a7c77af447814b216889aa3db482e2d560d244b14b29f039935
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\b3\03\54\9141c232861b89be935b37bdde0ea5ab472f5e18fc20623aed
Successfully built gym


In [5]:
import numpy as np

In [4]:
import gym
import random

In [6]:
env = gym.make("Taxi-v3")
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [7]:
state_space = env.observation_space.n

In [8]:
print("There are ", state_space," possible states")

There are  500  possible states


In [9]:
action_space=env.action_space.n
print("There are ", action_space," possible actions")

There are  6  possible actions


In [10]:
Q = np.zeros((state_space),(action_space))
print(Q)

TypeError: data type not understood

In [11]:
print(Q.shape)

NameError: name 'Q' is not defined

In [12]:
Q = np.zeros((state_space),(action_space))
print(Q)
print(Q.shape)

TypeError: data type not understood

In [13]:
Q = np.zeros((state_space,action_space))
print(Q)
print(Q.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(500, 6)


In [14]:
total_episodes = 25000
total_test_episodes = 100
max_steps = 200

learning rate=0.01
gamma=0.99

epsilon = 1.0
max_epsilon=1.0
min_epsilon=0.001
decay_rate=0.01

SyntaxError: invalid syntax (<ipython-input-14-dcd449c9f8f1>, line 5)

In [15]:
total_episodes = 25000
total_test_episodes = 100
max_steps = 200

learning_rate=0.01
gamma=0.99

epsilon = 1.0
max_epsilon=1.0
min_epsilon=0.001
decay_rate=0.01

In [16]:
#now we will define epsilon-greedy policy. this will handle with exploitation-exploration trade-off

In [17]:
def epsilon_greedy_policy(Q,state):
    if(random.uniform(0,1)>epsilon):
        action=np.argmax(Q[state]) #will go to maximum Q, i.e. exploitation; no RISK
    else:
        action=env.action_space.sample() #exploration
    return action 
            
        

In [18]:
env.action_space.sample()

4

In [19]:
env.action_space.sample()

1

In [20]:
env.action_space.sample()

1

In [21]:
env.action_space.sample()

3

In [22]:
#now we wil implement the Q learning algorithm.

In [27]:
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False

    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    
    for step in range(max_steps):
        #
        action = epsilon_greedy_policy(Q, state)

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        Q[state][action] = Q[state][action] + learning_rate * (reward + gamma * 
                                    np.max(Q[new_state]) - Q[state][action])      
        # If done : finish episode
        if done == True: 
            break
        
        # Our new state is state
        state = new_state

In [28]:
import time
rewards = []

frames = []
for episode in range(total_test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    print("****************************************************")
    print("EPISODE ", episode)
    for step in range(max_steps):
        env.render()     
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(Q[state][:])
        new_state, reward, done, info = env.step(action)
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episodes))

****************************************************
EPISODE  0
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : :_|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+------